import React, { useEffect, useState } from "react";
import { db } from "../../../firebase/firebase";
import { doc, getDoc } from "firebase/firestore";
import { connect } from "react-redux";
import { useTheme, useMediaQuery } from "@mui/material";
import { useRouter } from "next/router";
import Footer from "../../../Components/Footer/Footer";
import FooterLine from "../../../Components/Footer/FooterLine";
import Navbar from "../../../Components/Navbar/Navbar";
import Head from "next/head";
import OrderDetailsUser from "../../../Components/OrderDetails/OrderDetailsUser";

const OrderDetails = () => {
  const [isLoading, setIsLoading] = useState(true);
  const [orderData, setOrderData] = useState(null);
  const router = useRouter();
  const { slug, userId } = router?.query;
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("md"));

  useEffect(() => {
    async function fetchOrderData() {
      const docRef = doc(db, `users/${userId}/CartItems`, slug);
      const OrderData = await getDoc(docRef);
      setOrderData(OrderData.data());
      setIsLoading(false);
    }
    fetchOrderData();
  }, [router]);

  return (
    <>
      <Head>
        <title>Bravit | Order Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <OrderDetailsUser
        isMobile={isMobile}
        orderData={orderData}
        isLoading={isLoading}
      />
      <Footer />
      <FooterLine />
    </>
  );
};

const mapStateToProps = (state) => ({
  userData: state.user.userData,
  isLoggedIn: state.user.isLoggedIn,
});

const mapDispatchToProps = {};
export default connect(mapStateToProps, mapDispatchToProps)(OrderDetails);
