import React from "react";
import Navbar from "../Components/Navbar/Navbar";
import Head from "next/head";
import ImageHero from "../Components/Hero/ImageHero";
import OurMissionSlider from "../Components/ImageSlider/OurMissionSlider";
import Footer from "../Components/Footer/Footer";
import FooterLine from "../Components/Footer/FooterLine";

import HeaderImage from "../assets/Hero_Slider/Slider_1.png";
const about = () => {
  const activeTab = "/about";
  const selectedValue = 0;
  const HeroAlt = "Hero Image";
  const ImageHeading = "Test Hero";
  return (
    <>
      <Head>
        <title>Bravit | ABOUT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar activeTab={activeTab} selectedValue={selectedValue} />
      {/* <ImageHero
        HeroImage={HeaderImage}
        HeroAlt={HeroAlt}
        ImageHeading={ImageHeading}
      /> */}
      {/* <OurMissionSlider /> */}
      <Footer />
      <FooterLine />
    </>
  );
};

export default about;
