import React from "react";
import Navbar from "../Components/Navbar/Navbar";
import Head from "next/head";
import Footer from "../Components/Footer/Footer";
import FooterLine from "../Components/Footer/FooterLine";

const blog = () => {
  const activeTab = "/blog";
  const selectedValue = 0;
  return (
    <>
      <Head>
        <title>Bravit | BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar activeTab={activeTab} selectedValue={selectedValue} />
      <Footer />
      <FooterLine />
    </>
  );
};

export default blog;
