import React from "react";
import Navbar from "../Components/Navbar/Navbar";
import Head from "next/head";
import Footer from "../Components/Footer/Footer";
import FooterLine from "../Components/Footer/FooterLine";
import ContactUs from "../Components/ContactUs/ContactUs";

const contact_us = () => {
  const activeTab = "/contact_us";
  const selectedValue = 0;
  return (
    <>
      <Head>
        <title>Bravit | CONTACT US</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar activeTab={activeTab} selectedValue={selectedValue} />
      <ContactUs />
      <Footer />
      <FooterLine />
    </>
  );
};

export default contact_us;
