import { useRouter } from "next/router";
import React from "react";
import { connect } from "react-redux";
import { userLogoutSuccess } from "../redux/userSlice";
import Footer from "../Components/Footer/Footer";
import FooterLine from "../Components/Footer/FooterLine";
import Navbar from "../Components/Navbar/Navbar";
import Head from "next/head";

import {
  Box,
  Button,
  Typography,
  useTheme,
  useMediaQuery,
} from "@mui/material";
import UserProfile from "../Components/UserProfile/UserProfile";

const Dashboard = ({ isLoggedIn, userLogoutSuccess, userData }) => {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("md"));
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Bravit | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {isLoggedIn ? (
        <UserProfile userData={userData} />
      ) : (
        <Box
          sx={{
            width: isMobile ? "80%" : "60%",
            textAlign: "center",
            marginLeft: "auto",
            marginRight: "auto",
            padding: isMobile ? "10px 0px" : "40px 0px",
          }}
        >
          <Typography
            variant="h2"
            sx={{
              fontWeight: "bolder",
              padding: isMobile ? "10px 0px" : "30px 0px",
              fontFamily: "Montserrat, sans-serif",
              fontSize: isMobile ? "30px" : "60px",
              color: "#310a10",
            }}
          >
            you are not Logged in right now to access your details please Login.
          </Typography>
          <Button
            onClick={() => router.push("/login")}
            sx={{
              color: "#310a10",
              border: "2px solid #310a10",
              width: "60%",
              marginBottom: "20px",
            }}
          >
            Login
          </Button>
        </Box>
      )}
      <Footer />
      <FooterLine />
    </>
  );
};

const mapStateToProps = (state) => ({
  userData: state.user.userData,
  isLoggedIn: state.user.isLoggedIn,
});

const mapDispatchToProps = {
  userLogoutSuccess,
};
export default connect(mapStateToProps, mapDispatchToProps)(Dashboard);
