import Head from "next/head";
import React from "react";
import Navbar from "../Components/Navbar/Navbar";
import Footer from "../Components/Footer/Footer";
import FooterLine from "../Components/Footer/FooterLine";
import HeroSlider from "../Components/ImageSlider/HeroSlider";
import Products from "../Components/OurProducts/Products";
import { client } from "../lib/client";
import { useTheme, useMediaQuery } from "@mui/material";

const Our_Products = ({ products }) => {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("md"));
  const isLaptop = useMediaQuery(theme.breakpoints.between("md", "xl"));
  const activeTab = "/our_products";
  const selectedValue = 0;
  return (
    <>
      <Head>
        <title>Bravit | OUR PRODUCTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar activeTab={activeTab} selectedValue={selectedValue} />
      <HeroSlider />
      <Products products={products} isMobile={isMobile} isLaptop={isLaptop} />
      <Footer />
      <FooterLine />
    </>
  );
};

// export const getServerSideProps = async () => {
//   const query = '*[_type == "product"]';
//   const products = await client.fetch(query);

//   const bannerQuery = '*[_type == "banner"]';
//   const bannerData = await client.fetch(bannerQuery);

//   return {
//     props: { products, bannerData },
//   };
// };

export const getStaticPaths = async () => {
  const query = `*[_type == "product"] {
    slug {
      current
    }
  }
  `;

  const products = await client.fetch(query);

  const paths = products.map((product) => ({
    params: {
      slug: product.slug.current,
    },
  }));

  return {
    paths,
    fallback: "blocking",
  };
};

export const getStaticProps = async () => {
  const productsQuery = '*[_type == "product"]';

  const products = await client.fetch(productsQuery);

  return {
    props: { products },
  };
};

export default Our_Products;
