import Head from "next/head";
import React, { useEffect, useState } from "react";
import Navbar from "../Components/Navbar/Navbar";
import Footer from "../Components/Footer/Footer";
import FooterLine from "../Components/Footer/FooterLine";
import HeroSlider from "../Components/ImageSlider/HeroSlider";
import Products from "../Components/OurProducts/Products";
import { client } from "../lib/client";
import { useTheme, useMediaQuery } from "@mui/material";

const Our_Products = () => {
  const theme = useTheme();
  const [isLoading, setIsLoading] = useState(true);
  const [productData, setProductData] = useState(null);
  useEffect(() => {
    async function fetchProductData() {
      const productsQuery = '*[_type == "product"]';

      const products = await client.fetch(productsQuery);
      setProductData(products);
      setIsLoading(false);
    }
    fetchProductData();
  });

  const isMobile = useMediaQuery(theme.breakpoints.down("md"));
  const isLaptop = useMediaQuery(theme.breakpoints.between("md", "xl"));
  const activeTab = "/our_products";
  const selectedValue = 0;
  return (
    <>
      <Head>
        <title>Bravit | OUR PRODUCTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar activeTab={activeTab} selectedValue={selectedValue} />
      <HeroSlider />
      <Products
        products={productData}
        isMobile={isMobile}
        isLaptop={isLaptop}
        isLoading={isLoading}
      />
      <Footer />
      <FooterLine />
    </>
  );
};

export default Our_Products;
