import Head from "next/head";
import React from "react";
import Navbar from "../Components/Navbar/Navbar";
import Footer from "../Components/Footer/Footer";
import FooterLine from "../Components/Footer/FooterLine";
import HeroSlider from "../Components/ImageSlider/HeroSlider";

const our_products = () => {
  const activeTab = "/our_products";
  const selectedValue = 0;
  return (
    <>
      <Head>
        <title>Bravit | OUR PRODUCTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar activeTab={activeTab} selectedValue={selectedValue} />
      <HeroSlider />
      <Footer />
      <FooterLine />
    </>
  );
};

export default our_products;
